### ISSUE TITLE
Increased limits?

### ISSUE THREAD

**Issue by Razumen** [Shanjaq/uhexen2#30]
I've noticed with a lot of my new maps, especially since I've started using BSP2, that I've been running into issues that I think are caused by engine limits. One of them appears to be efrags limits which currently appears to prevent many entities from being rendered, but there's bound to be more if mappers want to take advantage of the larger map sizes possible, and I believe I haven't even really gotten close to what BSP2 can handle.

I've seen that some Quake sourceports like Fitzquake (http://www.celephais.net/fitzquake/) have increased [this limit and more](http://www.celephais.net/fitzquake/files/fitzquake085.txt). Would it be possible to port these over?

**Comment by Shanjaq** [comment]
resolved with #39
