### ISSUE TITLE
sounds cut shorter as game progresses

### ISSUE THREAD

**Issue by Shanjaq** [Shanjaq/uhexen2#33]
Sounds seem to get progressively more "interrupted" as the game runs longer, as if it's running out of channels when it shouldn't.

**Comment by Razumen** [comment]
I've noticed this as well, even at the start of a map. Sounds (ambient/monster/doors/some weapon sounds) seem to be cut off early.

**Comment by Shanjaq** [comment]
Resolved by #38

**Comment by Shanjaq** [comment]
fixed by #38
